In [ ]:
import pandas as pd
df = pd.read_csv('/train.csv')
print(df)
x=df['price_range']
print(x)
z=df.drop('price_range',axis=1)
print(z)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
c= scaler.fit_transform(z)
print(c)
print(c.shape)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]
(2000, 20)


In [ ]:
import pandas as pd
f = pd.read_csv('/test.csv')
print(f)

       id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       1           1043     1          1.8         1  14       0           5   
1       2            841     1          0.5         1   4       1          61   
2       3           1807     1          2.8         0   1       0          27   
3       4           1546     0          0.5         1  18       1          25   
4       5           1434     0          1.4         0  11       1          49   
..    ...            ...   ...          ...       ...  ..     ...         ...   
995   996           1700     1          1.9         0   0       1          54   
996   997            609     0          1.8         1   0       0          13   
997   998           1185     0          1.4         0   1       1           8   
998   999           1533     1          0.5         1   0       0          50   
999  1000           1270     1          0.5         0   4       1          35   

     m_dep  mobile_wt  ... 

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,z_train,z_test=train_test_split(c,x,test_size=0.75)
print(x_train)
print(x_test)
print(z_train)
print(z_test)
print(x_test.shape)
print(z_train.shape)
print(x_train.shape)
print(z_test.shape)


[[0.19505678 0.         0.28       ... 1.         1.         1.        ]
 [0.11088844 0.         0.32       ... 1.         0.         1.        ]
 [0.53974616 0.         0.24       ... 1.         0.         1.        ]
 ...
 [0.54843019 0.         0.72       ... 1.         0.         0.        ]
 [0.12157649 0.         0.08       ... 0.         0.         1.        ]
 [0.08149633 0.         0.36       ... 1.         0.         1.        ]]
[[0.70875084 1.         0.08       ... 0.         0.         0.        ]
 [0.65798263 0.         0.84       ... 0.         1.         0.        ]
 [0.50701403 1.         0.6        ... 1.         0.         1.        ]
 ...
 [0.29726119 1.         0.84       ... 0.         1.         0.        ]
 [0.93987976 0.         0.         ... 1.         0.         1.        ]
 [0.81629927 1.         0.2        ... 1.         1.         1.        ]]
541     3
1421    2
89      2
1844    0
1090    2
       ..
992     1
483     3
1755    3
1010    2
1620    2
Na

In [ ]:
import pandas as pd
x=pd.read_csv('/content/heart.csv')
print(x)
y=x['target']
print(y)
z=x.drop('target',axis=1)
print(z)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
A=scaler.fit_transform(z)
print(A)
print(A.shape)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]
(303, 13)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(A,y,test_size=0.25)
print(x_train)
print(x_test)
print(y_train)
print(y_test)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

[[0.25       1.         0.         ... 1.         0.         1.        ]
 [0.64583333 1.         0.         ... 1.         0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]
 ...
 [0.60416667 1.         0.66666667 ... 1.         0.5        1.        ]
 [1.         1.         0.         ... 1.         0.75       0.66666667]
 [0.25       1.         0.33333333 ... 1.         0.         0.66666667]]
[[0.83333333 1.         1.         0.62264151 0.24657534 1.
  0.         0.45801527 0.         0.01612903 0.5        0.25
  0.66666667]
 [0.64583333 0.         0.         0.52830189 0.30136986 0.
  0.         0.65648855 0.         0.41935484 0.5        0.5
  1.        ]
 [0.3125     1.         0.33333333 0.33962264 0.21232877 0.
  0.         0.89312977 0.         0.         1.         0.
  0.66666667]
 [0.60416667 1.         0.66666667 0.10377358 0.26027397 0.
  0.         0.63358779 1.         0.09677419 0.5        0.
  1.        ]
 [0.41666667 1.  

In [ ]:
x1=x_train[12]
print(x1)
x2=x_train[13]
print(x2)

[0.70833333 0.         0.         0.28301887 0.16210046 0.
 0.5        0.49618321 1.         0.         0.5        0.
 0.66666667]
[0.75       1.         0.         0.1509434  0.27853881 0.
 0.         0.66412214 0.         0.09677419 1.         0.5
 0.33333333]


In [9]:
import numpy as np
x1=x_train[0]
x2=x_train[1]
x3=x_train[2]
x4=x_train[3]
x5=x_train[4]
x6=x_train[5]
x7=x_train[6]
x8=x_train[7]
x9=x_train[8]
x10=x_train[9]
x11=x_train[10]
x12=x_train[11]
x13=x_train[12]
w_values = [w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13]
predictions = []

def perceptron(x_train, w_values, b):
    for x_sample in x_train:
        z = np.dot(x_sample, w_values) + b
        s = 1 / (1 + np.exp(-z))
        if s >= 0.5:
            predictions.append(1)
        else:
            predictions.append(0)

perceptron(x_train, w_values, b)
print(predictions)


IndexError: ignored